### ISSUE TITLE
0.8.4: Build fails: Not in scope: type constructor or class ‘CClockId’

### ISSUE THREAD

**Issue by willbasky** [corsis/clock#90]
The version of tools: ghc-8.6.5, cabal-3.2.0.0

The building of clock-0.8.4 fails. 
`cabal new-build --ghcjs`
```
Configuring library for clock-0.8.4..
Preprocessing library for clock-0.8.4..
Building library for clock-0.8.4..
[1 of 2] Compiling System.Clock     ( dist/build/System/Clock.hs, dist/build/System/Clock.js_o )

System/Clock.hsc:147:16: error:
    Not in scope: type constructor or class ‘CClockId’
    Perhaps you meant one of these:
      ‘ClockId’ (line 147), ‘CClock’ (imported from Foreign.C)
    |
147 | type ClockId = CClockId
    |                ^^^^^^^^
cabal: Failed to build clock-0.8.4
```

**Comment by CetinSert** [comment]
Is this specific to version `8.6.5` of `ghc`?
Is this an older version of `ghc`?

**Comment by willbasky** [comment]
I didn't check it with another versions of ghc. 
Yes, `8.6.5` is old one. But it is wanted for ghcjs compiling.

**Comment by willbasky** [comment]
btw, with `0.8.3` it built like a charm.

**Comment by phadej** [comment]
To clarify, it's not `ghc`, it's `ghcjs`. And indeed an old one. AFAIK `clock` doesn't work with GHCJS at all. I mean, it 0.8.3 compiles, but it doesn't actually work.

**Comment by willbasky** [comment]
Our project uses `extra-1.7.14` library which depends on `clock`. Well, it constraints with `(>=0.7)`.

**Comment by phadej** [comment]
@willbasky than I argue the issue is in `extra`. The functionality there which uses `clock` probably doesn't work. You just happen not to use it, but I'm sure it doesn't work. Try using [`duration`](https://hackage.haskell.org/package/extra-1.7.14/docs/System-Time-Extra.html#v:duration) for example.

And if it indeed doesn't work, you can open an issue in `extra` library. It may conditionally depend on `clock` like:

```
if !impl(ghcjs)
  build-depends: clock >=0.7.1
```

and have conditional code

```
#ifdef MIN_VERSION_clock
... clock
#else
... no clock
#endif
```

EDIT: One can argue that `clock` will be problematic dependency for upcoming WASM and JS GHC backends, so the conditional-code complexity will be there in the future anyway, even if GHCJS is currently quite an old thing, so IMO adding it now just prepares for the future.
